#' Function asocindex.It generates a data frame with the information required to calculate association indices, with the number of recruits observed under each canopy species and in the open for multiple study site. The function removes recruit species with a single individual
#'
#' @param inter a data frame with frequency of recruit under each canopy species and in the Open, in each study sites. It can be obtained extracting the first element of the list generated by the function plot_to_com.
#' @param Canopy_all a data frame with the cover of each canopy species, and open in each study site. It can be be obtained extracting the second element of the list generated by the function plot_to_com.
#' @param adjlist a list with the community matrix with recruit and canopy species in rows and columns respectively in each study site. It can be be obtained extracting the third element of the list generated by the function plot_to_com.
#'
#' @return a data frame with the number of recruits observed under each canopy species and in the open, with the relative cover of each canopy species and Open in each study site.
#' @export
#' @import dplyr
#'
#' @examples
#'
#'
#
#com<-plot_to_com (data,dbcover)
#asocindex(com[[1]],com[[2]],com[[3]])

asocindex <- function(inter=com[[1]],Canopy_all=com[[2]], adjlist=com[[3]]) {

  options(dplyr.summarise.inform = FALSE)


  edgelist <- list()

  for (z in 1:length(unique(Canopy_all$Study_site)))
  {

    mycovs <- Canopy_all[Canopy_all$Study_site == unique(Canopy_all$Study_site)[z], ]
    myadj <- adjlist[[unique(Canopy_all$Study_site)[z]]]


    #expando la base de datos de inetarcciones para que incluya los ceros de la matriz de interacciones

    obs_inter <- data.frame(expand.grid(dimnames(provideDimnames(myadj)))[1:2], as.vector(as.matrix(myadj)))

    colnames(obs_inter)[which(colnames(obs_inter) == "Var1")] <- "Recruit"
    colnames(obs_inter)[which(colnames(obs_inter) == "Var2")] <- "Canopy"
    colnames(obs_inter)[which(colnames(obs_inter) == "as.vector.as.matrix.myadj..")] <- "Freq"

    obs_inter$Study_site <-unique(Canopy_all$Study_site)[z]
     obs_inter$inter_ID <-
      paste(obs_inter$Study_site,
            obs_inter$Recruit,
            obs_inter$Canopy,
            sep = "_")


    #preparo database para calcular RII de casa interaccion
    openedge <- obs_inter[obs_inter$Canopy == "Open",c("inter_ID", "Freq" , "Study_site", "Canopy", "Recruit") ]
    myedge <- obs_inter[obs_inter$Canopy != "Open",c("inter_ID", "Freq" , "Study_site", "Canopy", "Recruit") ]

    # add Canopy_cover
    myedge <- merge(myedge, mycovs[, c("Canopy", "Canopy_cover")], by = "Canopy")
    #add Open cover

    myedge$Open_cover <- mycovs[mycovs$Canopy == "Open", "Canopy_cover"]


    #add number or recruits in open per recruit sp

    myedge <- merge(myedge, openedge[, c("Recruit", "Freq")], by = "Recruit", all.x = T)
    colnames(myedge)[which(colnames(myedge) == "Freq.x")] <- "Canopy_Freq"
    colnames(myedge)[which(colnames(myedge) == "Freq.y")] <- "Open_Freq"
    myedge[is.na(myedge$Open_Freq), "Open_Freq"] <- 0

    myedge <- myedge[which(myedge$Canopy_Freq + myedge$Open_Freq > 0), ]


    myedge<-myedge[,c("Study_site","Recruit","Canopy","inter_ID","Canopy_Freq","Canopy_cover","Open_Freq","Open_cover")]

    edgelist[[z]] <- myedge
    names(edgelist)[z] <- unique(Canopy_all$Study_site)[z]



  }

  db_inter <- data.frame(do.call("rbind", edgelist))

  db_inter$Freq_total <- db_inter$Canopy_Freq + db_inter$Open_Freq
  db_inter <- db_inter[db_inter$Freq_total > 1, ]   #We remove recruit species with just 1 individual

  return(db_inter)


}
