#' Function RII_index.It generates the relative association index described by Armas et al. XXX
#' #'
#' @param db_inter a data frame with frequency of recruit under each canopy species (named: Canopy_Freq, Canopy_Freq) and in the Open, and the percentage of cover occupied by each of them (named: Canopy_cover, Open_cover). It can be generated by the function "asocindex".
#'
#' @return the imputed data frame with a new column with the relative association index (RII)
#' @export
#' @import dplyr
#'
#' @examples
#'
#'
#
#com<-plot_to_com (data,dbcover)
#db_inter<-asocindex(com[[1]],com[[2]],com[[3]])
#RII<-asocindex(db_inter)

#calculates the RII observed for each interaction

RIIindex <- function(db_inter) {

  db_inter$RII <-
  with(db_inter, ((Canopy_Freq / Canopy_cover) - (Open_Freq / Open_cover)) /
         ((Canopy_Freq / Canopy_cover) + (Open_Freq / Open_cover)))

  return(db_inter)

}
