#' RII index
#'
#' It generates the relative association index described by Armas et al. 2002
#'
#' @param db_inter a data frame which must include at least seven columns named:
#' "Study_site","Recruit","Canopy","Canopy_Freq","Canopy_cover","Open_Freq",
#' "Open_cover" with frequency of recruits of each species under each canopy
#' species and in Open,(Canopy_Freq, Open_Freq), and the percentage of cover
#' occupied by each of them (named: Canopy_cover, Open_cover).
#' It can be generated by the function "asocindex".
#'
#' @return the imputed data frame with a new column with the relative association index (RII)
#'
#' @export
#' @import dplyr
#'
#' @examples
#' #com <- plot_to_com(data,dbcover)
#' #db_asoc <- asocindex(com[[1]], com[[2]], com[[3]])
#' #db_asoc <- asocindex(db_asoc)
#' #RII <- RIIindex(db_asoc)


#calculates the RII observed for each interaction

RIIindex <- function(db_inter, newarg = NULL) {

  db_inter$RII <-
  with(db_inter, ((Canopy_Freq / Canopy_cover) - (Open_Freq / Open_cover)) /
         ((Canopy_Freq / Canopy_cover) + (Open_Freq / Open_cover)))

  return(db_inter)

}
